[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91C94A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4ac76ff7c32be10d2f6da215f5e9b83
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91C95450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4ac76ff7c32be10d2f6da215f5e9b83
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91C11CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4ac76ff7c32be10d2f6da215f5e9b83