[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB2250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca69b9afa3fe8dc4d397669bc9d27386
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB2690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca69b9afa3fe8dc4d397669bc9d27386
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB29C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca69b9afa3fe8dc4d397669bc9d27386