[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB1040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e249f4c416333078e2f4bcdc510d56f2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB0E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e249f4c416333078e2f4bcdc510d56f2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B91CB1370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e249f4c416333078e2f4bcdc510d56f2